services:
  web:
    image: hrubech/myapp:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf