services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
 
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
