name: Docker Build & Push
on:
  push:
    paths:
      - 'Project3/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Project3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name:  Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
